image: python:3.12

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install --upgrade pip
  - pip install pytest flask flask-cors

test:
  stage: test
  script:
    - echo "Lancement des tests unitaires..."
    - pytest tests/ -v 
  only:
    - main
